modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]

modId="berryexpansion"
version="${file.jarVersion}"
displayName="BerryExpsion"
description='''

'''

[[dependencies.berryexpansion]]

   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.berryexpansion]]

   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"

[[dependencies.berryexpansion]]

    modId="byg"
    mandatory=false
    versionRange="[1.4-RC-10)"
    ordering="NONE"
    side="BOTH"